# Generated by Django 3.2.3 on 2022-06-01 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0003_picture_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ['title']},
        ),
    ]
